//given number N and modern phone keymap
//generate all possible strings generated by that number
//23
// AD,AE,AF,BD,BE,BF,CD,CE,CF
#include <iostream>
#include <cstring>
using namespace std;

string keypad[]={"","","ABC","DEF","GHI","JKL","MNO","PQRS","TUV","WXYZ"};
void printKeypadOutput(string input, string output, int i=0) {
    if (input[i]=='\0') {
        cout << output << endl;
        return;
    }

    int current_digit=input[i]-'0';
    if (current_digit==0 || current_digit==1) {
        printKeypadOutput(input,output,i+1);
    }
    for (int k=0;k<keypad[current_digit].size();k++) {
        printKeypadOutput(input,output+keypad[current_digit][k],i+1);
    }
}

int main() {
    string input="23";
    string output="";

    printKeypadOutput(input,output);
    return 0;
}

